### ISSUE TITLE
in route planner, add support for road elevation

### ISSUE THREAD

**Issue by mraross** [bcgov/api-specs#100]
This requires the ability to load road segments that have a third, Z coordinate for elevation and taking elevation into account when computing distance along a road segment.

This depends on the availability of BC Digital Road Atlas road segment data containing Z coordinates.

**Comment by cmhodgson** [comment]
We need more information about how we would get this data, what it is, and what would we do with it?

**Comment by mraross** [comment]
First determine what form of elevation data graphhopper needs.

**Comment by cmhodgson** [comment]
The Graphhopper routing algorithm supports 3-d points on the graph linework, which we load from the GeoJSON file that comes out of the geocoder processing, from ITN. We don't even need graphhopper to do anything, we would just calculate the weight of the segments based on the 3-d length rather than the 2-d length, assuming this is the goal of this ticket? We could also add a maximum grade restriction, by calculating and tagging every segment with the maximum grade?

In order to get the z-values onto the ITN we would need to conflate the MoT segments with the ITN, likely at every monthly data processing, which might be possible with FME, but might require a more complicated process. If the matching segments have different vertices, how would we distribute the Z-values along the matched segment, being careful not to affect the calculated grade? I've not yet seen a solution to this sort problem that is entirely automated.

A more realistic approach would be to calculate the 3-d distance on the MoT segments, and also potentially the maximum grade, and then add that information to the ITN road network, based on the ITN IDs - this makes the assumption that we have ITN IDs available in the MoT data, or some other way to easily match up the linestrings between ITN and MoT.

**Comment by mraross** [comment]
I like the realistic approach of computing 2.5D distance and maximum grade on road segments using MoT roads and possibly TRIM. This does sound like something GeoBC should be doing though.

**Comment by cmhodgson** [comment]
Have we resolved my comment from Nov 17? Do we know how we would get the z-values onto the linestrings?

**Comment by mraross** [comment]
GeoBC said they will be adding Z to road points by end of fiscal. They will be building a new DEM to drape the road geometry over. Does graphhopper handle (x,y,z) points?

**Comment by cmhodgson** [comment]
Yes. as I said earlier in the comments, graphhopper does support 3-d coordinates, we just have to tell it to do 3-d distance calcs. This should be fairly trivial, will just require some testing.

**Comment by mraross** [comment]
Issue moved to [bcgov/ols-router #19](https://github.com/bcgov/ols-router/issues/19) via [**ZenHub**](https://www.zenhub.com/)
