### ISSUE TITLE
Disallow U-turns at divided intersections

### ISSUE THREAD

**Issue by mraross** [bcgov/api-specs#101]
Here's a U-turn in a divided intersection:

Start: 988 Topaz Ave, Victoria, BC -123.360677,48.442561
End: 710 Redbrick St, Victoria, BC -123.368386,48.444587

https://router.api.gov.bc.ca/route.kml?points=-123.360677%2C48.442561%2C-123.368386%2C48.444587&outputSRS=4326&criteria=shortest&distanceUnit=km&apikey=yourApiKey

**Comment by cmhodgson** [comment]
Divided intersections are currently modeled as two separate intersections. In order to support this restriction, we would need to identify that these are actually the same intersection, and/or support turn restrictions in general.

**Comment by cmhodgson** [comment]
This is a duplicate of #69

**Comment by mraross** [comment]
Closed issue 69. Need to know if a change to ITN data model is required to support this restriction or if we can write a script to derive this restriction for every divided road intersection and what effort would be required.

**Comment by cmhodgson** [comment]
In the current ITN model, a U-turn at a divided intersection actually looks like two consecutive left turns, which are each possibly legal turns. It is only the two turns in succession that are not allowed, and graphhopper does not support such a restriction. We cannot disallow all cases of two left-turns in quick succession because in some places this is allowable and even necessary.

One approach would be to "pinch" the intersections together into a single point, and apply many turn restrictions to ensure correct travel, but it is not clear how well we can identify these intersections. It would also affect the visualization of the route, unless we did extra work to convert the intersection back to its non-pinched form after the routing work is done.

Another approach might be to assign identifiers to all such intersections, and prevent multiple turns made at the same intersection - but I'm not sure if we can do this restriction in graphhopper, either.

**Comment by gleeming** [comment]
The Enhanced Intersection data managed by GeoBC for ICBC maps each physical intersection point into logical intersections.  This might be useful in allowing us generate restrictions for standard double line intersection cases (1x2 or 2x2, plus possibly some turn lanes) and prevent U-turns,  However interchanges and larger complex intersections (some over 100 nodes) might be too broad to allow application of generic rules.

Not sure of the cost, openness or frequency of update of the EI data, so this may not really be suitable for our needs.

**Comment by cmhodgson** [comment]
Routing code should identify and prevent such u-turns at divided roads, programatically, at route-time.

**Comment by mraross** [comment]
Issue moved to [bcgov/ols-router #23](https://github.com/bcgov/ols-router/issues/23) via [**ZenHub**](https://www.zenhub.com/)
