### ISSUE TITLE
Upgrade to latest version of GraphHopper

### ISSUE THREAD

**Issue by mraross** [bcgov/api-specs#102]
Evaluate
a) if there are any enhancements or fixes that might be relevant to ORP
b) if the effort to integrate the new code is going to be cost-effective

**Comment by mraross** [comment]
What version of graph hopper does route planner 1.3 use?

**Comment by cmhodgson** [comment]
Router 1.3 is using GraphHopper 0.5, the latest is 0.8.3, after reviewing the changelog here:
https://github.com/graphhopper/graphhopper/blob/master/core/files/changelog.txt
I don't see anything particularly useful, however I do see many changes that will require changes in router to work with. From the graphhopper website it appears that most new features of interest are being implemented in the non-open graphhopper service api (ie. the service they are selling access to) rather than in the open source graphhopper code. That said, the graphhopper code isn't stale, but the changes appear to architectural refactoring in order to support the new features that are mostly being developed outside of the open source code.
That said, it may be worth trying to update the version, and seeing if the router code can be made compatible with the new version within say, an hour's or day's time - basically timebox a further investigation into how much effort it would take to integrate the latest graphopper, and either we successfully integrate it or we at least have a better idea of how long it will take.

**Comment by mraross** [comment]
Don't upgrade.
