### ISSUE TITLE
Missing unit number incorrectly faulted as UNIT_DESIGNATOR.notMatched

### ISSUE THREAD

**Issue by mraross** [bcgov/api-specs#120]
The following addresses:

```Unit -- 1359 Porlier Pass Rd, Galiano Island, BC```
```1359 Porlier Pass Rd APT, Galiano Island, BC```

both return a fault of:

```UNIT_DESIGNATOR.notMatched```

instead of: 

```UNIT_NUMBER.missing```

**Comment by cmhodgson** [comment]
There is no differentiation between unit designators that "need" a number or "can have" a number or "cannot have" a number. We did have this before but it was removed for some reason (there should be a ticket for it). Without that distinction, imagine that "unit" and "Apt" in the examples above are "bsmt". 

The only way to get a UNIT_NUMBER.missing fault is if you match the unit using a site name. Otherwise, input with a missing unit number would just match to the parent site.

**Comment by mraross** [comment]
Confirmed
