### ISSUE TITLE
Change how disconnected route points are handled

### ISSUE THREAD

**Issue by mraross** [bcgov/api-specs#129]
Add a routeFound property to results. Set to true if a route is found; false if route not found

If no route found, set output property values as follows:
1. start point as input
2. end point as input
3. an empty route geometry
4. routeFound set to false
5. routeDistance set to a distance bigger than the maximum distance between two points in BC  (e.g., 30,000 km)
6.  routeTime set to a large time period (e.g., 10,000 hr)

**Comment by cmhodgson** [comment]
Please review #64 - We already handle non-connected points with an error message. The KML handling of errors needs to be corrected. If you want to return a special result for KML output in these cases, I guess that is reasonable. The appropriate REST response might be 404 not found. We are currently returning 400  bad request. (but not for KML due to a bug identified in #64)

**Comment by mraross** [comment]
I don't think disconnected points is a bad request; its a route of infinite distance. That way, the application can decide how to handle it. . For example, if an application requests the fastest route between multiple source points and one target point, some routes might take infinite time but there will usually others that are much faster. This change in semantics would apply to all formats.

**Comment by cmhodgson** [comment]
From a REST perspective, you are looking for a resource which is the route between those two points. There is no such route; therefore: 404 not found. What you want to return is a "null object" - a representation of the non-existence of the route. That is OK, but not truly RESTful. I think that the reality is it may be more useful, particularly as the interface you prefer using (Google Earth) doesn't really support this aspect of REST (HTTP return codes with domain-relevant meanings). I guess this more OK because it is less of a resource and more of a "search results" sort of transient resource - it is the empty search result that is returned. I don't think that a very high time and distance are appropriate though; that could be misinterpreted as the route just being very large. I think a negative value (-1 or -9999 or similar) would be more appropriate.

**Comment by ll911** [comment]
@cmhodgson @mraross i think in those case, it should return 204 instead 404

**Comment by mraross** [comment]
For all output formats, when route planner has determined that route points are disconnected, return an HTTP response code of 200, a distance of -1, and a time value of "No route exists". In KML, just don't emit route polyline placemark and be sure to set distance and time properties in Router results <description> element appropriately.

**Comment by ll911** [comment]
here is google's direction api response status, I don't think 'NOT FOUND' is 200 https://developers.google.com/maps/documentation/directions/intro#StatusCodes

**Comment by cmhodgson** [comment]
Agree with Michael's note above, based on our conversation on the subject.
Leo, I believe http status of 204 is for successful operations which have nothing further to say in response; and example would be perhaps a "PUT" operation "Here server store this for me" and server responds with just "204 OK done no further response".

Our decision on this was that, instead of a 400-series failure message, we're going to give a "200 we successfully determined that there is no route between the points you gave, and here it is" and give back a "null result" with special values that allow the user to identify the lack of route.

**Comment by ll911** [comment]
@mraross @cmhodgson ok, I just tried, with google maps direction api, from whitehorse YT, to Kugluktuk, Nunavut on road, indeed it returns 200 HTTP status.

**Comment by cmhodgson** [comment]
The status that they are returning is in the JSON response, not in the HTTP response code. We do not currently have a status field, though it might be a good idea. The problem is that, if we return a 404 not found, along with an error message; google maps will not display that error anywhere to the user. The web browser also doesn't show you the 404 not found code, only whatever you put in the response document. So it is necessary to put something in the response that is understandable to the user. Basically, using response codes is handy for actual programs but putting the status in the response itself is no less useful for programs and also useful for humans. Doing both would be ok with me but makes the error response invisible in google earth.

**Comment by ll911** [comment]
maybe add status field to xml?

**Comment by mraross** [comment]
I think having special values in distance and time fields is sufficient for now. We will overhaul error handling in the future to include a standard error object.

**Comment by mraross** [comment]
How about adding a routeExists boolean property to the router results? routeExists = true if a route exists between the route start points and all stop points; false otherwise. We could also set distance and time to a large number (e.g., 60, 000, 000 and 1,000,000) so that all routes can be sorted properly whether they exist or not (e.g., non-existent routes will appear at the bottom of the shortest/fastest list) in routes/betweenPairs)

**Comment by mraross** [comment]
Verified in test
