### ISSUE TITLE
Geocoder API tolerates only 1 spelling error per word

### ISSUE THREAD

**Issue by xemoka** [bcgov/api-specs#134]
Hello, 

I'm using the Geocoder API to allow for autocomplete, it would be desirable if the API would show results when there are more than one character off the correct spelling: for example, when querying "710 Dickens" with a locality of "Warfield" the results will return 0 until "710 Dicken" is entered as a query (and not until then). The desired result would be that all possibilities are returned as they are requested—a search for "710 Di" would start to be populated by all possibilities. 

Sample search box: https://xemoka.github.io/bcgeocoder-search/ (repo: https://github.com/xemoka/bcgeocoder-search)

Thanks

**Comment by mraross** [comment]
I tried 302 Montcalm Rd in your autocompleting widget and it didn't start autocompleting when the civic number (302) was entered. The address finder widget does do this:

https://bcgov.github.io/ols-devkit/widget/

Since numbers are more selective and shorter than names, your widget might get better performance by starting on the civic number.

**Comment by mraross** [comment]
I did notice that the localities and notLocalities parameters are not configurable in our widget so I will request an enhancement for that support.

**Comment by cmhodgson** [comment]
Because the geocoder expects the addressString to be a COMPLETE address, the auto-completion function doesn't work similarly to many others. Furthermore, the localities and notLocalities parameters do not behave in the way you might expect - it doesn't help to narrow down the results until AFTER the addressString itself has already been parsed. For these reasons the autocomplete will never identify an address based purely on the civic number, even if it is the only such number in the specified locality, because (a) a civic number is not a valid address, so it doesn't parse as such (it parses only as a street name) and (b) the "localities" field is only used to filter the parsed matches, not to help with the parsing and identifying of matches. Also note that the the localities and notLocalities fields do not allow for any spelling errors (they aren't intended to handle user input) so you'd actually be better off just appending the locality field to the end of the user's input into the geocode field - but still, you will not get the same autocomplete results as you might expect from other similar services.

The Localities and notLocalities parameters ARE configurable on the widget (all parameters are passed through by prepending them with "data-") but they are not modifiable in the way that xemoka is using them (this is probably good for the reasons given above). They would be useful if someone was trying to make a geocoder widget work for only a reduced set of localities.

**Comment by mraross** [comment]
I believe Xemoka is trying to make the widget work for a reduced set of localities but I understand now why it wouldn't help improve the autocompletion experience.

**Comment by xemoka** [comment]
Yeah, I'm not sure you're autocompletion widget is much different from mine—just built from different tools. I end up with the same 'problem' of only allowing off-by-one-character completion.

I've tried appending the locality to the query and end up with the same issue too. Still constrained to the off-by-one-character limitation. 

If locality is an end filter instead of taken into consideration for the initial search I can see this being resource intensive on your end. I imagine on initial creation it wasn't intended to be used in autocompletion, and instead on either batch geocoding or single request?

**Comment by mraross** [comment]
The geocoder version now in test has a much improved autocomplete mode that works just like you expect. The addresses resource has a new autoComplete parameter that you set to true when you send a partial address for autocompletion.  Hint: As a user types into your address text box, set autoComplete with each geocode request but if the user clicks on the Search icon, set autoComplete to false since they consider the entered address complete.

You can see a demo of the new geocoder at https://cmhodgson.github.io/ols-devkit/ols-demo/index.html?env=tst

The demo app code is licensed under Apache 2.0 and is located at:
https://github.com/cmhodgson/ols-devkit/blob/gh-pages/ols-demo/index.html

**Comment by xemoka** [comment]
Thanks Michael, when I get some time back on that project I'll give it a shot—hopefully that time is coming soon.
