### ISSUE TITLE
Add a route planner resource that represents a given distance in a given direction from a given point on or near a road

### ISSUE THREAD

**Issue by mraross** [bcgov/api-specs#181]
Input parameters are:
point - a point on or near a DRA road segment or intersection
distance - distance to travel along road segment in given direction
direction - cardinal direction (e.g., N, S, E, W, NE, NW, SE, SW) to travel in

**Comment by mraross** [comment]
For example, an accident report comes in with the location described as 14 km north of Boulder St, Dease Lake on the Cassiar Highway. 

1. You enter the intersection, _boulder st and cassiar hwy, dease lake_  into the address or location text box and press search. A  geocoder /addresses request is made and the map zooms to the intersection. 

2. You enter 14 N and hit the _Travel_ icon. A router/travel request is made, and the map zooms north 14 km and displays the coordinates and DRA block ID in an incident reporting form.

3. You then complete the form with the gory details.

**Comment by cmhodgson** [comment]
This difficulty in doing this is I have to traverse the graphopper graph, which so far I haven't had to work with directly - just call functions to build and functions to route.

**Comment by cmhodgson** [comment]
We also have to think about how we handle weird situations - the road doesn't go as far as you asked, or the road forks and has the same name on both side (typical of the loop at the end of a lollipop-type culdesac )

**Comment by mraross** [comment]
Instead of start point, direction, and road name parameters, how about start point, end point, and  distance parameters. The system then adjusts the end point back along the shortest/fastest route or forward along the last named street to make the required distance between start and end points.

Here's  the revised interaction for recording an accident report with the location described as 14 km north of Boulder St, Dease Lake on the Cassiar Highway.

1. You enter the intersection, boulder st and cassiar hwy, dease lake into the starting point box and press search. A geocoder /addresses request is made and the map zooms to the intersection.

2. On the map, you select the end point box, click a second point on the Cassiar Hwy just a short distance and north from the start point. The coordinates of the point are copied into the end address box. 

3. You enter 14 into the distance box and press the Route button. The system issues a router/travel request with the start/end points and distance=14. The system receives a response with an end point 14 km north and displays the route on the map.  

You enter 14 N and hit the Travel icon. A router/travel request is made, and the map zooms north 14 km and displays the coordinates and DRA block ID in an incident reporting form.

You then complete the form with the gory details.

**Comment by cmhodgson** [comment]
This implies that I can infer the road name based on the two points being closest to at least some segments sharing the same same name. If the end point is not nearest to a segment which shares a name with the the segment(s) nearest the start point, we return an error. This approach also assumes that the user has a start point on the segment, if instead the start point is a landmark which is not directly on the segment, then we have to guess the street name based on the nearest segment to the end point (if the end point is an intersection or perhaps slightly closer to the wrong segment due to an input error, this would not work well). Given that this is a visual, interactive process, I think a user could probably work through it but as an API it seems problematic to use.

Also, to be consistent with the rest of the API, I would expect the distance to be in meters, not km.

**Comment by mraross** [comment]
Not needed after all
