### ISSUE TITLE
Unusual address interpolation on Merridale Rd, Cobble Hill

### ISSUE THREAD

**Issue by mraross** [bcgov/api-specs#187]
1230 Merridale not at end of  street. Google puts it in the right place.
Civic numbers increase in both directions.

**Comment by mraross** [comment]
![geocoder_701 apr 24 15 21](https://cloud.githubusercontent.com/assets/11318574/25361243/fcfee254-2901-11e7-9eac-1284d2bcc04f.jpg)
![geocoder_700 apr 24 15 20](https://cloud.githubusercontent.com/assets/11318574/25361242/fcfd6f64-2901-11e7-9b4d-9aabe9276238.jpg)

**Comment by cmhodgson** [comment]
There is an error in the RNF data. There are two segments with ranges from 1230-1254 and 1230-1290 (starting from the dead end of the road). In these cases we pick one of the duplicate psuedo-sites, and we picked the wrong one, and there is not enough other data to sort it out so the error comes through in the results. Perhaps when we have duplicate psuedo-sites we should just throw them all out rather than pick one potentially wrong one.

**Comment by cmhodgson** [comment]
#220 describes the fix for this problem.

**Comment by mraross** [comment]
Why is 1230 Merridale Rd, Cobble Hill, BC not at the end of the road. It is slightly west of it.

**Comment by cmhodgson** [comment]
#221 has the answer and is the ticket explaining this problem. (I originally entered #220 minutes before Graeme entered the more descriptive #221)

**Comment by mraross** [comment]
Verified in delivery
