### ISSUE TITLE
Add a time-dependent penalty to turns at intersections

### ISSUE THREAD

**Issue by mraross** [bcgov/api-specs#192]
Add a penalty to route cost for each turn at an intersection. For example, turning left should be penalized more than turning right which should be penalized more than heading straight through. 

Ideally, time-dependent turn penalties should be based on data coming from a Provincial Traffic Service that provides real-time and historic traffic data. If no such service is forthcoming, historic traffic data from the BC Ministry of Transportation and Infrastructure and BC municipalities should be used.

**Comment by cmhodgson** [comment]
The code for adding intersection delays is already written. The difficulty is in fixing the data so that when the router uses the turn delays, weird things don't happen. We propose spending 1-2 days investigating the problems in the data to better understand their nature. We should the discuss them with the ITN team to see if they are interested in working towards resolving them, and/or if we need to figure out how to resolve them on our end. Issues we know about involving turn restrictions on channelized right-turn lanes would best be handled (stored) in ITN.

**Comment by mraross** [comment]
Route Planning in Road Networks with Turn Costs
http://algo2.iti.kit.edu/documents/routeplanning/volker_sa.pdf

**Comment by mraross** [comment]
Issue moved to [bcgov/ols-router #18](https://github.com/bcgov/ols-router/issues/18) via [**ZenHub**](https://www.zenhub.com/)
