### ISSUE TITLE
in geocoder admin app, limit localities that an alias can map to, to ITN localities

### ISSUE THREAD

**Issue by mraross** [bcgov/api-specs#202]
In geocoder admin:
1. select locality mappings
2. In Input text box, enter Queen Charlotte City
3. In Maps to pick list, look for Queen Charlotte. You will only find Queen Charlotte, Village of.

Why isn't Queen Charlotte in the pick list?

**Comment by cmhodgson** [comment]
Because "Queen Charlotte, Village of" is the official name?

**Comment by cmhodgson** [comment]
Sorry. Queen Charlotte IS in the list, the list is just ordered poorly and contains all of the GNIS localities which it should NOT. This is probably a bug from when we made the admin app separate from the geocoder itself.

**Comment by mraross** [comment]
Gotcha. Locality aliases need to be in the ITN. This means we can suggest them to GeoBC but we can't add them ourselves?

**Comment by cmhodgson** [comment]
The locality that the alias points at must be in ITN, because that is what the actual sites themselves are attached to - they are attached to the ITN segments, which have ITN locality ids on them. I'm just changing the admin app code right now to only include the ITN localities in the pick list (and list them alphabetically).

**Comment by mraross** [comment]
Sounds good.

**Comment by mraross** [comment]
Confirmed in delivery.
