### ISSUE TITLE
Street level geocodes with ampersand returning match with missing space

### ISSUE THREAD

**Issue by mraross** [bcgov/api-specs#21]
Geocoding 7016 L & A Rd Vernon BC works fine. Geocoding L & A Rd Vernon BC returns a street level match for one of the generated aliases: L &A Rd, Vernon, BC (or L& A Rd).

Perhaps the geocoder logic for street comparisons is converting & to 'And' then back but not handling the leading and/or trailing spaces correctly?

**Comment by cmhodgson** [comment]
I got Graeme to prevent generation of aliases such as "L &A" or "L& A" for "L & A". However, we do create  aliases of "L" and "A" for "L & A" and the same thing is done if they were full words instead of single letters. The result is that it is interpreted as an intersection between "L" street and "A" street, which are really both "L & A" street, but this matches to every intersection between L & A and any other street and with a higher score than the street-level match that you are looking for. This doesn't seem like a great result but it is somewhat difficult, as in the case of  "L & A" street intersecting itself, this is probably the right answer.

**Comment by mraross** [comment]
Verified in delivery
