### ISSUE TITLE
civic number suffix not being matched

### ISSUE THREAD

**Issue by BK01** [bcgov/api-specs#226]

**Comment by mraross** [comment]
The results of the request:
https://delivery.apps.gov.bc.ca/pub/geocoder/sites/within.html?excludeUnits=true&brief=true&bbox=-116.522648,49.148549,-116.505568,49.16174

include 749E Lakeview Arrow Creek Rd, Wynndel, BC and 810E 749E Lakeview Arrow Creek Rd, Wynndel, BC

but the request for either of these addresses returns a full address without the civicNumberSuffix. For example, try this:
https://delivery.apps.gov.bc.ca/pub/geocoder/addresses.html?addressString=810E+Lakeview+Arrow+Creek+Rd%2C+Wynndel%2C+BC

**Comment by mraross** [comment]
Oddly enough, civicNumberSuffix is properly matched for this address:
4251A Rockbank Pl, West Vancouver, BC

Try this:
https://delivery.apps.gov.bc.ca/pub/geocoder/addresses.html?addressString=4251A+Rockbank+Pl%2C+West+Vancouver%2C+BC

**Comment by cmhodgson** [comment]
The issue is that the suffix "e" is an ordinal in french, similar to "th" in english, and we presently remove all ordinals from number immediately and without prejudice. However, in this case we want to also allow for the alternative interpretation of a number with a suffix of "e". I have implemented this now locally and it seems to be working well.

**Comment by cmhodgson** [comment]
Working in delivery now.

**Comment by mraross** [comment]
Verified in delivery

**Comment by mraross** [comment]
verified in prod
