### ISSUE TITLE
Duplicate addresses with odd civicNumbers

### ISSUE THREAD

**Issue by mraross** [bcgov/api-specs#239]
Is this due to a data prep script or address range generator problem or is it purely a source data problem? 

6l Elasgenze Dr, Dease Lake, BC
 -  civicNumber=6, civicNumberSuffix=1
 -  should be 16 Elasgenze Dr given neighbouring civic numbers
 - address appears twice in sites with different site ids 

7l Elasgenze Dr, Dease Lake, BC
 -  civicNumber=7, civicNumberSuffix=1
 -  should be 17 Elasgenze Dr given neighbouring civic numbers
 - address appears twice in sites with different site ids

**Comment by mraross** [comment]
![geocoder_785 sep 06 09 39](https://user-images.githubusercontent.com/11318574/30123680-a66a581a-92e7-11e7-85ff-0bb2e3633a22.jpg)
![geocoder_786 sep 06 09 40](https://user-images.githubusercontent.com/11318574/30123684-aa975226-92e7-11e7-9d5b-37d379f4042a.jpg)

**Comment by mraross** [comment]
In Prod, there are duplicates but in test there aren't. In the screenshots above, you can see 6 Elasgenze Dr and 6I Elasgenze Dr;  7 Elasgenze Dr, 7I Elasgenze Dr. This suggests that there is probably nothing wrong with the data prep scripts, just the data.

**Comment by gleeming** [comment]
The source address list data from BCA has records with an 'l' instead of a '1':
 2016,25,Northwest,787,Dawson Creek Rural (787),82952120,l7 ELASGENZE DR DEASE LAKE,,l7,,ELASGENZE,DR,,DEASE LAKE
 2016,25,Northwest,787,Dawson Creek Rural (787),82952130,l6 ELASGENZE DR DEASE LAKE,,l6,,ELASGENZE,DR,,DEASE LAKE

In the current processing scripts, these are now rejected because the filter for civic numbers only allows digits followed by an optional space, 1/2 or single character for parsing into suffix components.  The preceding 'l' violates this rule.

However recovery site data from v3.0 prod to "gap fill" includes this previously accepted combination, so these two cases are directly fed back into the active site stream with already parsed civic suffixes of 'l'.  They could probably be deleted from that recovery input file and reported back to BCA.

There appear to be several other related cases, 36 of which also made it in the recovery file, e.g.
 2016,04,Central Vancouver Island,315,North Cowichan (315),08053312,62l6 LOWER CHIPPEWA RD DUNCAN,,62l6,,LOWER CHIPPEWA,RD,,DUNCAN
 2016,08,North Shore-Squamish Valley,748,Squamish Rural (748),02860420,l730 REID RD MOUNT CURRIE,,l730,,REID,RD,,MOUNT CURRIE
 2016,21,Nelson/Trail,413,Creston (413),00188000,8l3 CANYON ST CRESTON,,8l3,,CANYON,ST,,CRESTON

**Comment by cmhodgson** [comment]
This problem was identified in prod, is fixed in test, and we confirm that we expect it to remain fixed, I don't think there is any further action and this?

**Comment by gleeming** [comment]
The only thing fixed is how the FME scripts now parse source data to filter out illegal combinations of civic/suffixes.  The unexpected entry looks and acts like a real site in prod.  This has then propagated back to delivery and test through the re-feed file.

It should disappear during the next processing run if we either a) remove the offending addresses from the re-feed file (HybridPost input) or b) eliminate HybridPost input entirely.

**Comment by mraross** [comment]
Good point. The plan is to eliminate the need for the hybridPost file when the new BC Assessment data prep script is complete and tested.

**Comment by mraross** [comment]
Verified in prod
