### ISSUE TITLE
Add support for an address history file

### ISSUE THREAD

**Issue by mraross** [bcgov/api-specs#262]
An address history file contains a table of mappings between a previous address its current address. For example, Abbotsford Middle School at  2222 Ware St, Abbotsford, BC was torn down and a new one built in its place with a new address of 33231 Bevan Ave, Abbotsford, BC. Another example is the house at 238 Leon Ave, Kelowna, BC paid to have its civic number changed to 240.

 The address history file for these two examples would look like this:
oldAddress,newAddress
"2222 Ware St, Abbotsford,BC","33231 Bevan Ave, Abbotsford, BC"
"238 Leon Ave, Kelowna, BC","240 Leon Ave, Kelowna, BC"

An address can have more than one previous addresses but each oldAddress requires a separate row.

The address history file is to be used during geocoding like an alias address table, attempting to find a match to an old address and returning the new one.

**Comment by cmhodgson** [comment]
Some concerns about this:
- There would need to be some way to make it clear to the user what is going on (I guess a fault could explain it) 
- What if the old address has been reused?
- What if the old address is no longer valid, eg. there is no road segment with an address range including the old civic number? And/or the street name has changed? The "old" addresses would need to be attached to some street segment somewhere in order to be found at all. 
For renumbering cases, the linear approximation is going to be pretty close to the right address anyway, for case involving moving the access to a different street it seems awfully confusing and again, the old address will get you to the right place, you may just need to turn the corner to get to the access ... if you are looking for a business then the named-based lookup will give you the current address

**Comment by mraross** [comment]
Issue moved to [bcgov/ols-geocoder #45](https://github.com/bcgov/ols-geocoder/issues/45) via [**ZenHub**](https://www.zenhub.com/)
