### ISSUE TITLE
In addresses resource, add support for handling space between number and ordinal in numbered street name

### ISSUE THREAD

**Issue by mraross** [bcgov/api-specs#268]
For example
`1020 W 1 st ave, vancouver, bc`

should be changed to:

`1020 W 1st ave, vancouver, bc`

**Comment by cmhodgson** [comment]
Done. The specific example "1020 W 1 st ave, vancouver, bc" is troubling because there is no 1020 on that street in Vancouver, (at least in my current data) so it prefers to match "1020 W 1st St, North Vancouver, BC" with locality.isAlias and streetType.notMatched faults - but if you change it to 102 it works fine.

**Comment by cmhodgson** [comment]
Confirmed working in delivery:
http://delivery.apps.gov.bc.ca/pub/geocoder/addresses.html?addressString=102%20W%201%20st%20ave,%20vancouver,%20bc

**Comment by mraross** [comment]
Verified in Test
