### ISSUE TITLE
Add support for offline geocoding

### ISSUE THREAD

**Issue by mraross** [bcgov/api-specs#269]
An offline geocoder doesn't need to be hooked up to the web to work. It could take the form of a containerized API or a standalone desktop Java app.

Requested by Elections BC for use onsite at polling stations during elections

**Comment by ll911** [comment]
docker package and allow to run locally or anywhere

**Comment by cmhodgson** [comment]
Not sure that a docker package would be an acceptable solution for the clients in mind (on-site elections registration was one?) due to complexities of install and system requirements - however, if the geocoder is to run in its present form this is probably the most straightforward way to package up all of the components.

An alternative approach would be a java desktop app of some kind, a simpler install, potentially reduced requirements, but does require much more work to create it.

**Comment by mraross** [comment]
Issue moved to [bcgov/ols-geocoder #44](https://github.com/bcgov/ols-geocoder/issues/44) via [**ZenHub**](https://www.zenhub.com/)
