### ISSUE TITLE
unit before site name not recognized as such

### ISSUE THREAD

**Issue by mraross** [bcgov/api-specs#278]
If you geocode the following address:

`Art Deco Building -- 22470 Dewdney Trunk Rd unit 170, Maple Ridge, BC`

you get the following correct response:

`UNIT 170 -- 22470 Dewdney Trunk Rd, Maple Ridge, BC`
`score=90, matchPrecision=UNIT, faults={SITE_NAME.notMatched,10}`

but if you enter the following variation of the same address:

`unit 170, Art Deco Building -- 22470 Dewdney Trunk Rd, Maple Ridge, BC`

the geocoder doesn't recognize the unit:

`22470 Dewdney Trunk Rd, Maple Ridge, BC`
`score=90, matchPrecision=CIVIC_NUMBER,faults={SITE_NAME.notMatched,10; MAX_RESULTS.too_low_to_include_all_best_matches,0}`

In current production release, the second example is correctly handled

**Comment by mraross** [comment]
In Prod,  the address

unit 170, Art Deco Building -- 22470 Dewdney Trunk Rd, Maple Ridge, BC

has two responses that are identical (including a score of 90) except one has a matchPrecision of UNIT and the other CIVIC_NUMBER. So the crux of the problem seems to be not penalizing the CIVIC_NUMBER match when a reference UNIT_NUMBER is known.

**Comment by cmhodgson** [comment]
The correct site name in delivery is Douglas College, as seen here:
https://delivery.apps.gov.bc.ca/pub/geocoder/addresses.html?minScore=50&maxResults=5&echo=false&brief=true&autoComplete=true&addressString=UNIT%20170%20Douglas%20College%20--%2022470%20Dewdney%20Trunk%20Rd,%20Maple%20Ridge,%20BC

But this does not exist in prod due to the occupant not existing in prod.

**Comment by mraross** [comment]
Verified in prod

**Comment by mraross** [comment]
Verified in test
