### ISSUE TITLE
civic address at end of block assigned accessPoint in middle of intersection

### ISSUE THREAD

**Issue by mraross** [bcgov/api-specs#282]
Geocode the following address with locationDescriptor=accessPoint:

3101 30th Ave, Vernon, BC

https://apps.gov.bc.ca/pub/geocoder/addresses.json?minScore=50&maxResults=5&echo=false&brief=true&autoComplete=true&addressString=3101+30+Ave%2C+Vernon%2C+&locationDescriptor=accessPoint

The resulting accessPoint is at the correct latitude but not the correct longitude. It is east of the eastern-most parcel boundary and in the middle of the intersection.

![image.png](https://images.zenhubusercontent.com/57a52ca5e40e5714b16d039c/c60da3b1-f0b4-4224-b9d0-9e139fd8a238)

**Comment by cmhodgson** [comment]
I have now changed this behaviour so that there is a "intersection offset" distance from either end of the segment that is equal to 1/2 the road width as is calculated to determine the curb offset of access points along the road. Address numbers which are past the last real civic address point on the segment will be interpolated between that point and a point which is the "intersection offset distance" inset from the end of the line. If the last real civic address point is closer to the end of the line than the intersection offset distance, any civic number beyond it will interpolate the same point. To test this, check that to addresses on either side of block division are not in the same location but are offset some distance, eg. 1299 and 1301 were exactly on top of each other before this change, now they are a (calculated) road's width apart.

**Comment by cmhodgson** [comment]
There was a further problem related to this - the Rangebuilder was not assigning some address points to the correct segments. It turned out the that there was a bug in the distance calculation code that essentially used the distance from the address point to the bounding box of the segment when selecting the nearest segment. 

Correcting this to use the actual distance to the line segment caused the rangebuilder to drop a small number (121) of address points due to being too far away. However, the
"total Address Coverage" increased by over 10% from 31,629,419 to 34,899,895 and the number of addressed block faces increased by 51,000 from 356,045 to 407,034. The address range "stretching" logic was much more successful after this change, this is what caused most of the increase in address coverage - this is the result of the better consistency between the initially determined ranges, which are based on the initial placement of addresses onto the nearest correctly-named segment.

The results are quite evident when comparing maps of address points and the associated access points before and after this fix; it has become much more rare to see an access point exactly on the end of a segment, and in general the access points are always on the nearest point of the line to the address point (as has always been the intention).

**Comment by mraross** [comment]
Verified in delivery
