### ISSUE TITLE
Only result is province of BC in many cases

### ISSUE THREAD

**Issue by OKNoah** [bcgov/api-specs#346]
When the search string is just a number, and the `matchPrecisionNot` is set to `PROVINCE`, the only result I get is the province of BC itself.

```zsh
curl "https://geocoder.api.gov.bc.ca/addresses.json?autoComplete=true&addressString=5068&matchPrecisionNot=PROVINCE,LOCALITY"
```

**Comment by OKNoah** [comment]
Using the Swagger UI, the default example for `/occupants/addresses.{outputFormat}` also just returns BC.

**Comment by cmhodgson** [comment]
You will not get any matches for a query of 5068, even with autocomplete on - you must have at least 3 characters, and the trailing word must be the start of a street or locality name. Searching for addresses by unit number or civic number alone is not supported.

The default behaviour of the geocoder is to return a "BC" match when no match is found. Presently some of the query filter options (such as matchPrecisisonNot) are not applied to this default match. After a short discussion we have decided that all such filters should be applied.

The occupant example query (and some of the details of the occupant query) in the API console is out of date. These will be updated.

**Comment by mraross** [comment]
Thanks for the bug report OKNoah. We have updated the example in the Swagger UI and will get the bug fixed in the next release sometime in the fall. Note in the previous API version, a front gate ("--") was required to tell the geocoder that the input was an occupant name and not an address. In the current API version, no delimiter is required to indicate an occupant name. For example:<br>
`sir james douglas elementary`

If you want to include a partial or complete address, you now just add an occupant separator ("**") followed by a partial or complete address as in:<br>
`sir james douglas elementary ** Victoria`

**Comment by mraross** [comment]
Verified
