### ISSUE TITLE
Insufficient anchor points on segment

### ISSUE THREAD

**Issue by BK01** [bcgov/api-specs#380]
The correct location of the following address is not found using adaptive or linear. Rather a block level match is found.

4760 Roger St, Port Alberni, BC

Following review of surrounding sites as well as intersections we can see that insufficient anchor points are available per segment for successful adaptive interpolation. In particular the segment of Roger St closest to the address is broken by an emergency lane.

**Comment by cmhodgson** [comment]
It is true that there are two many segments with no enough address points. However it is weird that the access point for 4780 Roger St is so far down the road, rather than being placed on the segment immediately in front of the parcel. I suspect that anchor points from other sources are making this worse instead of better. There is definitely room for smarter address assignment logic in cases where there is a shortage of information (likely only a couple of anchor points and a single parcel point). The extra segment breaks due to the rail crossing and emergency lane work against the post-smoothing logic, as does the apparent offset in addressing between the sides of street, and the existence of the same-name side-street branches.

**Comment by mraross** [comment]
I added an additional address on each side of the emergency lane (4760 and 4724) to sites_databc.csv. That should give the address range maker a little more grist for the mill.

**Comment by mraross** [comment]
Issue moved to [bcgov/ols-geocoder #30](https://github.com/bcgov/ols-geocoder/issues/30) via [**ZenHub**](https://www.zenhub.com/)
