### ISSUE TITLE
GeoJSON file review

### ISSUE THREAD

**Issue by BK01** [bcgov/api-specs#386]
After downloading a GeoJSON file (polygon - single - WEB MERCATOR) and submitting to a validator the following message was received.

"Invalid GeoJSON
 Line 1: old-style crs member is not recommended
 Line 1: Polygons and MultiPolygons should follow the right-hand rule"

**Comment by pauldaustin** [comment]
The official GeoJSON spec (https://tools.ietf.org/html/rfc7946) now only allows data in WGS84.
 
When we developed Geomark the  [GJ2008] spec (no longer published) allow the specification of coordinate systems.
 
Do you want me to remove the option from downloading Geomarks using GeoJson in any format other than WGS84?
 
I'm also going to change it so that the WGS84 output will not include the coordinate system specification so that it is a valid document.
 
[GJ2008]   Butler, H., Daly, M., Doyle, A., Gillies, S., Schaub, T., and C. Schmidt, "The GeoJSON Format Specification", June 2008.

**Comment by pauldaustin** [comment]
The "Polygons and MultiPolygons should follow the right-hand rule" is actually a red herring. The geometries are written using the right hand rule (counter-clockwise exterior rings). It's just the validator gets confused if the geometry is not in WGS84.

**Comment by BK01** [comment]
Agreed. Please remove the ability to download GeoJson in formats other than WGS84.

**Comment by BK01** [comment]
Correct behaviour verified in DLV (6.0.0-SNAPSHOT)

**Comment by mraross** [comment]
Elections BC will now have to change their script. Hopefully, it won't be a major inconvenience to them.

**Comment by pauldaustin** [comment]
My advice would be for them to switch to TSV with WKT encoded geometry.

GeoJson adds little value in this use case.

**Comment by BK01** [comment]
Validated in DLV.
