### ISSUE TITLE
in geocoder/addresses.json, streetName sometimes returned as a number instead of a string

### ISSUE THREAD

**Issue by pramsey** [bcgov/api-specs#4]
Here's the query:

http://apps.gov.bc.ca/pub/geocoder/addresses.geojson?addressString=19089+FSR+0069,+PINK+MOUNTAIN,+BC

The malformation happens in the `streetName` attribute, where the value returned is:

```
"streetName":0069
```

Ordinarily, `streetName` is a string, but in this case, perhaps because all the characters are digits, it is handled as a number. Trouble is, it's an illegal number (at least, according to both the JSON parsers I've sent it through. The leading double-zero makes them angry. Probably `streetName` should just ever and always be a string, since that's how it's interpreted programatically. (You'd never do math on one, for example).

**Comment by pramsey** [comment]
A similar problem can occur when `unitNumber` includes a leading zero.
```
"unitNumber":02
```

**Comment by mraross** [comment]
Good snag.  Have opened a geocoder defect report on this.

**Comment by cmhodgson** [comment]
I fixed my json output code to not output numbers with leading zeros as numerics (ie. do quote them). However, ITN has since renamed this road to have a name_body of "FSR 0069", and no type; this is the only case of "FSR" not being a type, and the only case of leading zeroes in the street number. Good on PR for finding it.

**Comment by mraross** [comment]
Verified in delivery

**Comment by mraross** [comment]
verified in test
