### ISSUE TITLE
in address prep, when duplicates are found, pick the one closest to the street.

### ISSUE THREAD

**Issue by mraross** [bcgov/api-specs#52]
![geocoder_515 sep 14 08 31](https://cloud.githubusercontent.com/assets/11318574/18518747/276984aa-7a56-11e6-81a5-1633a77024b8.jpg)

The address closest to the street is closer to the house that is being addressed. This wont always be true but will be true more often than a parcel centroid.

**Comment by gleeming** [comment]
This is not possible to do easily with our current approach.  A lot of logic currently handled in FME would need to be recoded in Java.

Candidate sites are initially geocoded at a street level match precision to canonicalize the name for block assignment.  After scoring, full address duplicates are then pre-filtered in FME based on custodial source precedence.  At that time the points have not yet been assigned to a segment from which the closest could be determined.

The only way to accomplish the ticket objective would be to get FME to export all sites as candidates for block assignment (doubling the number of inputs) and have the Java BAARG software implement a mix of precendence and proximity rules.  All of the child/parent relationship logic currently in FME would also have to be moved over to Java so subsites could get correctly allocated once the preferred parent ID was selected.  Also the SID2PID logic would need to be moved over so that the JUROL would be linked to the correct SID of whichever parent record was ultimately selected.

Seems like a lot of unnecessary work in converting over unrelated chunks of code just for the benefit of being able to implement a closest test.

**Comment by mraross** [comment]
Confirmed
