### ISSUE TITLE
Duplicate civic addresses loaded which are street aliases of each other in Clinton

### ISSUE THREAD

**Issue by mraross** [bcgov/api-specs#53]
The following addresses are in the same parcel:
1208 Kelly Lake Rd
1208 Pavillion-Clinton Rd

They are street aliases of each other.  The following civic numbers also have duplicate addresses:

1001,1003,1005,1007,1009,1011,1203
1000,1004,1008,1100,1104,1108,1112,1116,1118,1122,1120,1200,1204,

**Comment by mraross** [comment]
![geocoder_515 sep 14 08 31](https://cloud.githubusercontent.com/assets/11318574/18519644/88fa6434-7a59-11e6-8cc7-1c79b3bae934.jpg)

**Comment by gleeming** [comment]
ITN and TNRD web map show Kelly Lake Rd stopping at the edge of the municipality of Clinton, then carrying on as Pavilion-Clinton Rd further west.  In ITN the ranges for Kelly Lake Rd are from 1000-1219.

In BCA is a record for 1204 KELLY LAKE RD Clinton BC which gets properly allocated to nearby ITN segment with that name.  This is the address for the RCMP detachment in Clinton.

In AddressBC is a record for 1204 PAVILION-CLINTON RD Clinton BC which gets allocated to the first ITN segment off to the west that shares that primary name.  Even though it is a more accurate rooftopPoint representation, its access point gets stuck 500m away due to the name differences.

Links:
http://tnrdmap.tnrd.ca/PropertyReport/Property_Report_P10463.pdf
http://www.rcmp.gc.ca/detach/en/d/192#Clinton

**Comment by gleeming** [comment]
![clinton_53](https://cloud.githubusercontent.com/assets/21045965/18525415/41b9a8ce-7a71-11e6-88f9-e664880e619a.jpg)

**Comment by cogborne** [comment]
In the ITN we will  rename 375008,546719,546720 to Pavillion-Clinton Rd with an alias of Kelly Lake Rd and adjust the address ranges as required. There are no address points for 1208 Kelly Lake Rd according to TNRD. They have 1208 Pavillon-Clinton Rd. They also have 1120 Pavillion-Clinton in LTSA parcel ID 009052461 and 1122 in 009052488
![capture](https://cloud.githubusercontent.com/assets/8249077/25247919/30ca4f5e-25c1-11e7-9dda-fa7133327772.JPG)

**Comment by mraross** [comment]
On Thu 2017-04-20 11:41 AM, Mark Harris wrote:

All the addresses that you reported to us as incorrect in January 24, 2017 are correct in our database today.  The only address I could not find is 1122.  There are no addresses in Clinton at 1122 according to our database.  

In https://bcgov.github.io/ols-devkit/ols-demo/index.html I found 1122 Pavilion-Clinton Rd, Clinton, BC but we have the same parcel as 1120 KELLY LAKE RD CLINTON in eValueBC.

**Comment by mraross** [comment]
Verified
