### ISSUE TITLE
street direction prefix treated like civic number suffix in delivery and prod

### ISSUE THREAD

**Issue by mraross** [bcgov/api-specs#61]
650 South Terminal Ave nanaimo bc 

returns the following address:

650S Terminal Ave, Nanaimo, BC

and the following faults:

[CIVIC_NUMBER_SUFFIX.notMatched:1, MAX_RESULTS.too_low_to_include_all_best_matches:0]

It should have returned 650 S Terminal Ave, Nanaimo, BC with a streetDirection.notMatched fault

**Comment by gleeming** [comment]
Note that it does return 650 Terminal Ave, Nanaimo, BC with a streetDirection.notMatched fault at the same max score.  However abbreviations should probably not be used for civic and unit suffixes.

**Comment by cmhodgson** [comment]
This was a bit tricky but I was able to resolve it.

**Comment by mraross** [comment]
Any hints on how to test? What might the tricky bits cause to fail?

**Comment by cmhodgson** [comment]
I guess the concern would be that suffixes would be broken as a result of the changes but they seem to be working fine. I had to change the place in the code that suffixes were identified - I was worried that there wouldn't be a way to do this but the fix actually turned out to be pretty simple once I figured it out. Not tricky in the "had to hack in a fix" way, tricky in the, "hey I just realized that there was already a way to do this" kind of way :)

**Comment by cmhodgson** [comment]
Confirmed in delivery.

**Comment by mraross** [comment]
Verified in delivery with the following:

650 South Terminal Ave nanaimo bc => streetDirection.notMatched
650S Terminal Ave nanaimo bc  => civicNumberSuffix.notMatchetched

**Comment by mraross** [comment]
650 S Terminal Ave nanaimo bc gives the following:
650S South Terminal Ave nanaimo bc => civicNumberSuffix.notMatched

which is incorrect as per the original issue

**Comment by cmhodgson** [comment]
For the input of: 
650 S Terminal Ave nanaimo bc 
(which was not the input string in the original issue)

I do not get the result:
650S **South** Terminal Ave nanaimo bc => civicNumberSuffix.notMatched

but I do get (no **South**):
650S Terminal Ave nanaimo bc => civicNumberSuffix.notMatched

Which is a valid interpretation: S is a civicNumberSuffix, and civicNumberSuffixes are allowed to have a space between them and the civic number. 

If you increase the number of maxResults, you also get a case of:
650 Terminal Ave Nanaimo BC => STREET_DIRECTION.notMatched

Which is another valid interpretation which happens to have the same score as the first case.

**Comment by mraross** [comment]
Rejected in delivery. Unless the civicNumberSuffix is a fraction, no space is allowed between civicNumber and civicNumberSuffix. 

Here is the Canada Post definition of civicNumberSuffix which is what :

Civic number suffix (if present) should be placed after the civic number as follows:
 - without a space between the civic number and the civic number suffix, if the suffix is alpha (i.e. a letter)
-  with one space between the civic number and the civic number suffix, if the suffix is a fraction

CivicNumberSuffix is defined on p. 67 of the Physical Address Conceptual Model although, looking at it now, its a bit subtle. I will add the text above from the Canada Post standard to the Conceptual Model document and the Single-Line Format document.

**Comment by cmhodgson** [comment]
When possible, we generally accept things as long as we can determine what they are. Why would we change our code to no longer accept a space between the civic number and and civic number suffix? This "error" doesn't affect what is accepted, it only affects the faults given by ONE of the matches. The fix you suggest causes us to no longer match a bunch of inputs that we previously would have.

An alternative would be to sort matches with identical scores so that the one with the higher matchPrecision is always first. This is probably a good idea in any case of equal scores, and in this case would allow your preferred faults to be the first result returned.

**Comment by mraross** [comment]
I agree that we want robust parsing but not at the expense of misleading faults. Your suggestion of sorting results by matchPrecision is brilliant. Please make it so.

**Comment by cmhodgson** [comment]
Done, works great.

**Comment by mraross** [comment]
Verified in delivery

**Comment by mraross** [comment]
Verified in test
