### ISSUE TITLE
Add new resource called addresses/singleLine that takes an addressString but no structured address elements

### ISSUE THREAD

**Issue by mraross** [bcgov/api-specs#63]
Such a resource has far fewer input parms and is much easier for developers to understand.

**Comment by mraross** [comment]
Be sure to include support for new brief parameter

**Comment by cmhodgson** [comment]
Is this not just an alias to the existing /addresses ? I assume it needs to support things like localites/notLocalities, matchPrecision/matchPrecisionNot? Do we just need better documentation?

**Comment by mraross** [comment]
Yes it is. It is necessary because the REST API Console, which replaced our online geocoder app, arranges all input parms in a single column list which makes it virtually unusable. By eliminating all structure address parms, the list is a lot shorter. I guess one alternative is to have an advance address tab in the demo app that allows you to control more input parameters?

**Comment by cmhodgson** [comment]
Is it possible to do the alias in the middleware? Or just add a duplicate URL with a shorter parameter list to your API definition file? This really feels like a documentation issue, not a code issue. If anything, I would like to create an alias which still supports ALL of the parameters, but you just document only the ones you want to. Otherwise every new parameter brings with it the question of, "does the simpler version support this?". Also, can we just call it addresses/simple ? or something like that? "singleLine" already has meaning in roads-land that isn't related to this use. The word "simple" is often used to denote easier-to-use interfaces without being derogatory or negative.

**Comment by mraross** [comment]
This enhancement is not necessary.
