### ISSUE TITLE
in geocoder/addresses, unit not recognized if input contains a siteName

### ISSUE THREAD

**Issue by mraross** [bcgov/api-specs#77]
Given a site with the following address:

   UNIT 170 -- 22470 Dewdney Trunk Rd, Maple Ridge, BC

If a geocoder/addresses request has an addressString that contains a site name as in:

   Douglas College, UNIT 170 -- 22470 Dewdney Trunk Rd, Maple Ridge, BC

the geocoder returns the following:

   Douglas College UNIT 170 -- 22470 Dewdney Trunk Rd, Maple Ridge, BC

which is missing a comma between the echoed test (e.g., "Douglas College") and UNIT 170

Here is a test request

http://test.apps.gov.bc.ca/pub/geocoder/addresses.json?addressString=Douglas%20College%20UNIT%20170%20--%2022470%20Dewdney%20Trunk%20Rd%2C%20Maple%20Ridge%2C%20BC

**Comment by mraross** [comment]
Occupants/addresses also not correct:

http://test.apps.gov.bc.ca/pub/geocoder/occupants/addresses.html?addressString=Douglas%20College%20%20unit%20170%20--%20%2022470%20Dewdney%20Trunk%20Rd,%20Maple%20Ridge,%20BC&echo=false

**Comment by cmhodgson** [comment]
To fix this, I've added a parse path for <sitename> <unit description> <frontgate> <civicaddress>, which makes the occupant example work perfectly, but has the interesting side affect of "correcting" the order of the site name and unit number of the site example to "UNIT 170 DOUGLAS COLLEGE -- 22470 Dewdney Trunk Rd, Maple Ridge, BC" - this is because it interprets the site name to be OF the unit, not of a subsite of the unit. Is this an acceptable result?

**Comment by mraross** [comment]
Yes, that is acceptable given that going further is very tricky.

**Comment by mraross** [comment]
Verified in delivery
