### ISSUE TITLE
in occupant prep script, accept occupants with unmatched units

### ISSUE THREAD

**Issue by mraross** [bcgov/api-specs#8]
Currently, an occupant with an unmatched unit will be rejected.For example, if a site exists for 1175 Douglas St,Victoria but not for 310-1175 Douglas St, the latter will be rejected.

Instead of rejecting these occupants, there are two options that would allow us to load it:
1. Create a subsite of the root site and set unitDesignator, unitNumber, and unitNumberSuffix appropriately.
2. Create a site with a non-civic address using locality determined from the lat/lon and ITN locality coverage, and the parcelPoint set to the lat/lon.

Option 1 seems more satisfying.

**Comment by gleeming** [comment]
I just came up with a simplified approach that should be much easier to implement and not require a feedback loop at the end of the process.  The concept is to initially screen/geocode/parse records up front against the current operational data, instead of doing this at the end against the new data being refreshed.  The only downside is very minor -- we'll reject unit candidates that might otherwise have been salvaged if their parent isn't currently in the operational data but will be newly included in the refresh.

Here's the basic logic:
1) write a new FME script to output a batchable file of all GSR civic occupant addresses
2) pre-geocode those full address strings against the operational full geocoder data
3) modify the GSR FMI to add suitable candidates into the master site prep stream
  - read in the results of the batch run
  - candidate cases will be site-matches that have only a unit fault
  - since they will have nicely parsed out civic and unit fields from the geocoder, we can format these additional CAP entries as if they had been given structured address fields from GSR
  - they will be output alongside the existing GSR NCAP records already being extracted in the FMI
4) modify the site loader prep FMW that gets run against the results of the usual site-batching at street level precision
  - add GSR as the lowest priority source for duplicate address resolution of CAPs
  - prevent orphaned GSR unit CAP candidates from creating parents (should rarely occur if the parent record got retired since the last data update) -- just drop them if they don't have an active parent in the working set
5) the rest of the process from BAARG and beyond shouldn't require any changes

**Comment by mraross** [comment]
Another way to handle an occupant with an unknown unit of a known site is to simply attach the occupant to the known site.

**Comment by gleeming** [comment]
I implemented this based on the proposed approach in my Sept. 30 comment.  A test example is
207-5462 Trans Canada Highway, Duncan BC which is not a site in v3.1 but now shows up in v3.2.

**Comment by mraross** [comment]
Verified in prod
